const tattingar = [
  [
    'Fåglar',
    'Tättingar',
    'Kråkfåglar',
    'Skata',
    'Pica pica',
    'male',
    'Råstasjön',
    'stockholm',
    '2009-05-15',
    'image067.jpg',
  ],
  [
    'Fåglar',
    'Tättingar',
    'Kråkfåglar',
    'Kråka',
    'Corvus corone',
    'female',
    'Råstasjön',
    'stockholm',
    '2009-05-15',
    'image068.jpg',
  ],
  [
    'Fåglar',
    'Tättingar',
    'Kråkfåglar',
    'Råka',
    'Corvus frugilegus',
    'male',
    'Verkeån',
    'skane',
    '2010-05-19',
    'image066.jpg',
  ],
  [
    'Fåglar',
    'Tättingar',
    'Kråkfåglar',
    'Lavskrika',
    'Perisoreus infaustus',
    'male',
    'Ånnsjön',
    'jamtland',
    '2010-06-16',
    'image069.jpg',
  ],
  [
    'Fåglar',
    'Tättingar',
    'Kråkfåglar',
    'Kaja',
    'Corvus monedula',
    'male',
    'Ottenby',
    'Öland',
    '2009-07-12',
    'image070.jpg',
  ],
  [
    'Fåglar',
    'Tättingar',
    'Kråkfåglar',
    'Nötskrika',
    'Garrulus glandarius',
    'male',
    'Källhagen',
    'sodermanland',
    '2018-04-28',
    'image301.jpg',
  ],

  [
    'Fåglar',
    'Tättingar',
    'Mesar',
    'Talgoxe',
    'Parus major',
    '',
    'Källhagen',
    'Sörmland',
    '2019-05-07',
    'image1003.JPG',
  ],

  [
    'Fröväxter',
    'Gömfröiga',
    'Lövträd',
    'Oxel',
    '',
    'Sorbus intermedia',
    'Högenäs orde',
    'Öland',
    '2017 -08-03',
    'image409.jpg',
  ],
  [
    'Fröväxter',
    'Gömfröiga',
    'Lövträd',
    'Rönn',
    '',
    'Sorbus aucuparia',
    'Furudal',
    'Dalarna',
    '2017-09-01',
    'image410.jpg',
  ],
];

export const defaultTatting = (id = 0) => ({
  species: tattingar[id][3],
  place: tattingar[id][6],
  date: tattingar[id][8],
  kingdom: tattingar[id][0],
  order: tattingar[id][1],
  family: tattingar[id][2],
  county: tattingar[id][7],
  speciesLatin: tattingar[id][4],
  sex: tattingar[id][5],
  image: tattingar[id][9],
});
